import {createFileRoute,Link} from '@tanstack/react-router';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {useServerFn} from '@tanstack/react-start';
import {useState} from 'react';
import {Plus,Download,Pencil,Trash2,X,Package} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {getAdminData,saveProduct,removeProduct} from '@/lib/catalogue.functions';
import {meta,money,brands} from '@/lib/store';
import {useStore} from '@/components/store-shell';
export const Route=createFileRoute('/admin')({staticData:{sitemap:"exclude-subtree"},head:()=>meta('Store management','Owner-only product and order management for L.W Pet Care.','/admin',{noindex:true}),component:Admin});
function Admin(){const {userName}=useStore();const fetchAdmin=useServerFn(getAdminData);const save=useServerFn(saveProduct);const remove=useServerFn(removeProduct);const qc=useQueryClient();const {data,error,isLoading}=useQuery({queryKey:['admin',userName],queryFn:()=>fetchAdmin(),enabled:!!userName,retry:false});const [tab,setTab]=useState('Products');const [editing,setEditing]=useState<string|null>(null);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const current=data?.products.find(p=>p.id===editing);const variant=current?.product_variants[0];
 if(!userName)return <main className="wrap section"><div className="page-head"><h1>Store management</h1><p>Sign in with your owner account to manage the store.</p><Button asChild><Link to="/account">Sign in</Link></Button></div></main>;
 if(error)return <main className="wrap section"><h1>Owner access required</h1><p>{error.message}</p><p>Contact the store owner to request access.</p></main>;
 if(isLoading)return <main className="wrap section"><p>Loading your store…</p></main>;
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const f=Object.fromEntries(new FormData(e.currentTarget));try{await save({data:{id:current?.id,name:String(f['name']),slug:String(f['slug']),brand:String(f['brand']),category:String(f['category']),pet_type:String(f['pet_type']),life_stage:String(f['life_stage']),description:String(f['description']),status:f['status']==='published'?'published':'draft',image_url:String(f['image_url']??''),pack_size:String(f['pack_size']),price:f['price']?Number(f['price']):null,mrp:f['mrp']?Number(f['mrp']):null,stock:Number(f['stock']||0),sku:String(f['sku']??'')}});setEditing(null);setMessage('Product saved.');qc.invalidateQueries({queryKey:['admin']});qc.invalidateQueries({queryKey:['catalogue']});}catch(error){setMessage(error instanceof Error?error.message:'Unable to save.')}finally{setBusy(false)}}
 return <main className="wrap section"><div className="section-heading"><div><h1 className="font-display text-3xl">Your store, at a glance</h1><p>Louis Wilson Pet Care · Owner workspace</p></div><Button onClick={()=>setEditing('new')}><Plus/>Add product</Button></div><div className="trust-inner mb-6"><div><strong>{data?.products.length??0}</strong><p className="text-xs text-muted-foreground">Catalogue products</p></div><div><strong>{data?.orders.length??0}</strong><p className="text-xs text-muted-foreground">Orders</p></div><div><strong>{money(data?.orders.filter(o=>o.status==='Paid').reduce((sum,o)=>sum+o.total,0)??0)}</strong><p className="text-xs text-muted-foreground">Paid revenue</p></div><div><strong>{data?.products.filter(p=>p.status==='draft').length??0}</strong><p className="text-xs text-muted-foreground">Draft products</p></div></div><div className="admin-tabs">{['Products','Orders','Customers'].map(t=><Button key={t} variant={t===tab?'default':'outline'} onClick={()=>setTab(t)}>{t}</Button>)}{tab==='Products'&&<Button variant="outline" onClick={()=>{const rows=[['Name','Brand','Category','Status','Pack size','MRP','Price','Stock','SKU'],...(data?.products??[]).map(p=>[p.name,p.brand,p.category,p.status,p.product_variants[0]?.pack_size,p.product_variants[0]?.mrp,p.product_variants[0]?.price,p.product_variants[0]?.stock,p.product_variants[0]?.sku])];const csv=rows.map(r=>r.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download='lw-pet-care-products.csv';a.click();URL.revokeObjectURL(url)}}><Download/>Export CSV</Button>}</div>{message&&<p className="form-message" role="status">{message}</p>}
 {editing!==null&&<section className="mb-10 border border-border rounded-lg p-6"><div className="section-heading"><h2>{current?'Edit product':'Add product'}</h2><Button variant="ghost" size="icon" onClick={()=>setEditing(null)} aria-label="Close product form"><X/></Button></div><form onSubmit={submit} key={editing} className="form-grid">{[['name','Product name',current?.name],['slug','URL slug',current?.slug],['image_url','Product image URL',current?.image_url],['pack_size','Pack size',variant?.pack_size],['mrp','MRP (₹)',variant?.mrp],['price','Selling price (₹)',variant?.price],['stock','Stock',variant?.stock],['sku','SKU',variant?.sku]].map(([name,label,value])=><label key={String(name)} className="text-xs">{label}<input className="field mt-2" name={String(name)} defaultValue={value??''} type={['price','mrp','stock'].includes(String(name))?'number':'text'} min="0" required={name==='name'||name==='slug'}/></label>)}<label className="text-xs">Brand<select name="brand" className="field mt-2" defaultValue={current?.brand}>{brands.map(b=><option key={b}>{b}</option>)}</select></label><label className="text-xs">Category<select name="category" className="field mt-2" defaultValue={current?.category}>{['Dog Food','Cat Food','Treats','Toys','Vet Diets','Grooming & Care'].map(c=><option key={c}>{c}</option>)}</select></label><label className="text-xs">Pet type<select name="pet_type" className="field mt-2" defaultValue={current?.pet_type}><option value="dog">Dog</option><option value="cat">Cat</option></select></label><label className="text-xs">Life stage<select name="life_stage" className="field mt-2" defaultValue={current?.life_stage}>{['puppy','kitten','adult','senior'].map(s=><option key={s}>{s}</option>)}</select></label><label className="text-xs">Description<textarea name="description" className="field mt-2" defaultValue={current?.description}/></label><label className="text-xs">Visibility<select name="status" defaultValue={current?.status??'draft'} className="field mt-2"><option value="draft">Draft</option><option value="published">Published</option></select></label><Button type="submit" disabled={busy}>{busy?'Saving…':'Save product'}</Button></form></section>}
 {tab==='Products'&&<table className="admin-table"><thead><tr><th>Product</th><th>Brand</th><th>Status</th><th>Price</th><th>Stock</th><th>Actions</th></tr></thead><tbody>{data?.products.map(p=><tr key={p.id}><td>{p.name}</td><td>{p.brand}</td><td>{p.status}</td><td>{p.product_variants[0]?.price!=null?money(p.product_variants[0].price):'—'}</td><td>{p.product_variants[0]?.stock??'—'}</td><td><Button size="icon" variant="ghost" title="Edit product" aria-label={'Edit '+p.name} onClick={()=>setEditing(p.id)}><Pencil/></Button><Button size="icon" variant="ghost" title="Delete product" aria-label={'Delete '+p.name} onClick={async()=>{if(!window.confirm('Delete '+p.name+'?'))return;try{await remove({data:{id:p.id}});qc.invalidateQueries({queryKey:['admin']});qc.invalidateQueries({queryKey:['catalogue']})}catch(error){setMessage(error instanceof Error?error.message:'Unable to delete.')}}}><Trash2/></Button></td></tr>)}</tbody></table>}
 {tab==='Orders'&&(data?.orders.length?<table className="admin-table"><thead><tr><th>Order</th><th>Status</th><th>Total</th><th>Date</th></tr></thead><tbody>{data.orders.map(o=><tr key={o.id}><td>{o.id.slice(0,8)}</td><td>{o.status}</td><td>{money(o.total)}</td><td>{new Date(o.created_at).toLocaleDateString('en-IN')}</td></tr>)}</tbody></table>:<div className="empty-state"><Package size={35}/><h2>No orders yet</h2></div>)}
 {tab==='Customers'&&<table className="admin-table"><thead><tr><th>Name</th><th>Mobile</th></tr></thead><tbody>{data?.customers.map(c=><tr key={c.id}><td>{c.name||'Customer'}</td><td>{c.mobile||'—'}</td></tr>)}</tbody></table>}</main>
}
