import {createFileRoute,notFound} from '@tanstack/react-router';
import {useSuspenseQuery} from '@tanstack/react-query';
import {useState} from 'react';
import {catalogueOptions} from '@/lib/catalogue.functions';
import {CatalogueError} from '@/components/shop-page';
import {Button} from '@/components/ui/button';
import {meta,money,whatsapp} from '@/lib/store';
export const Route=createFileRoute('/product/$slug')({loader:async({context,params})=>{const products=await context.queryClient.ensureQueryData(catalogueOptions);if(!products.some(p=>p.slug===params.slug))throw notFound();},head:({params})=>meta(params.slug.replace(/-/g,' '),'Explore pet nutrition and essentials at L.W Pet Care.'),errorComponent:CatalogueError,notFoundComponent:()=> <div className="wrap section"><h1>Product not available</h1><p>This product is not yet on our online shelves.</p></div>,component:Product});
function Product(){const {slug}=Route.useParams();const {data}=useSuspenseQuery(catalogueOptions);const p=data.find(p=>p.slug===slug);const [index,setIndex]=useState(0);const [pincode,setPincode]=useState('');const [message,setMessage]=useState('');if(!p)return null;const variant=p.product_variants[index];return <main className="wrap section"><div className="detail-layout">{p.image_url&&<img src={p.image_url} alt={p.name}/>}<div><div className="eyebrow">{p.brand}</div><h1 className="font-display text-3xl">{p.name}</h1><p className="text-muted-foreground">{p.description}</p><div className="flex gap-2 my-5">{p.product_variants.map((v,i)=><Button variant={i===index?'default':'outline'} key={v.id} onClick={()=>setIndex(i)}>{v.pack_size}</Button>)}</div>{variant?.price!=null&&<h2>{money(variant.price)} <small className="text-muted-foreground text-xs">GST included</small></h2>}<p>{variant&&variant.stock>0?'Available in store':'Contact us for availability'}</p><Button asChild><a href={whatsapp+'?text='+encodeURIComponent('Hi! I would like to enquire about '+p.name+' '+(variant?.pack_size??''))} target="_blank" rel="noreferrer">Enquire on WhatsApp</a></Button><form className="flex gap-2 mt-6" onSubmit={e=>{e.preventDefault();setMessage(/^\d{6}$/.test(pincode)?'Free home delivery across Delhi NCR. Contact us to confirm your area.':'Enter a valid 6-digit pincode.')}}><input className="field" aria-label="Delivery pincode" value={pincode} onChange={e=>setPincode(e.target.value)} maxLength={6} placeholder="Delivery pincode"/><Button variant="outline" type="submit">Check</Button></form><p className="mt-3 text-xs">{message}</p></div></div>{[['Description',p.description],['Key benefits',p.benefits],['Ingredients',p.ingredients],['Feeding guide',p.feeding_guide]].filter(([,value])=>value).map(([name,value])=><section key={name} className="article"><h2>{name}</h2><p>{value}</p></section>)}<div className="article"><h2>Reviews</h2><p>No reviews yet.</p></div></main>}
