CREATE TYPE public.app_role AS ENUM ('admin','user');
CREATE TABLE public.user_roles(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid NOT NULL,role public.app_role NOT NULL,UNIQUE(user_id,role));
GRANT SELECT ON public.user_roles TO authenticated; GRANT ALL ON public.user_roles TO service_role;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
CREATE POLICY own_roles ON public.user_roles FOR SELECT TO authenticated USING(user_id=auth.uid());
CREATE FUNCTION public.has_role(_user_id uuid,_role public.app_role) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT EXISTS(SELECT 1 FROM public.user_roles WHERE user_id=_user_id AND role=_role) $$;
CREATE TABLE public.profiles(id uuid PRIMARY KEY,name text NOT NULL DEFAULT '',mobile text NOT NULL DEFAULT '',created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT,UPDATE ON public.profiles TO authenticated; GRANT ALL ON public.profiles TO service_role;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY own_profile ON public.profiles FOR ALL TO authenticated USING(id=auth.uid()) WITH CHECK(id=auth.uid());
CREATE POLICY admin_profiles ON public.profiles FOR SELECT TO authenticated USING(public.has_role(auth.uid(),'admin'));
CREATE TABLE public.addresses(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid NOT NULL REFERENCES public.profiles(id),name text NOT NULL,mobile text NOT NULL,pincode text NOT NULL,address text NOT NULL,city text NOT NULL,state text NOT NULL);
GRANT SELECT,INSERT,UPDATE,DELETE ON public.addresses TO authenticated; GRANT ALL ON public.addresses TO service_role;
ALTER TABLE public.addresses ENABLE ROW LEVEL SECURITY;
CREATE POLICY own_addresses ON public.addresses FOR ALL TO authenticated USING(user_id=auth.uid()) WITH CHECK(user_id=auth.uid());
CREATE TABLE public.products(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),name text NOT NULL,slug text NOT NULL UNIQUE,brand text NOT NULL DEFAULT '',category text NOT NULL DEFAULT 'Dog Food',pet_type text NOT NULL DEFAULT 'dog',life_stage text NOT NULL DEFAULT 'adult',breed_size text NOT NULL DEFAULT 'all',description text NOT NULL DEFAULT '',benefits text NOT NULL DEFAULT '',ingredients text NOT NULL DEFAULT '',feeding_guide text NOT NULL DEFAULT '',image_url text,status text NOT NULL DEFAULT 'draft',created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT ON public.products TO anon; GRANT SELECT,INSERT,UPDATE,DELETE ON public.products TO authenticated; GRANT ALL ON public.products TO service_role;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
CREATE POLICY published_products ON public.products FOR SELECT TO anon,authenticated USING(status='published');
CREATE POLICY admin_products ON public.products FOR ALL TO authenticated USING(public.has_role(auth.uid(),'admin')) WITH CHECK(public.has_role(auth.uid(),'admin'));
CREATE TABLE public.product_variants(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),product_id uuid NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,pack_size text NOT NULL DEFAULT '',mrp numeric,price numeric,stock integer NOT NULL DEFAULT 0,sku text UNIQUE);
GRANT SELECT ON public.product_variants TO anon; GRANT SELECT,INSERT,UPDATE,DELETE ON public.product_variants TO authenticated; GRANT ALL ON public.product_variants TO service_role;
ALTER TABLE public.product_variants ENABLE ROW LEVEL SECURITY;
CREATE POLICY public_variants ON public.product_variants FOR SELECT TO anon,authenticated USING(EXISTS(SELECT 1 FROM public.products WHERE id=product_id AND status='published'));
CREATE POLICY admin_variants ON public.product_variants FOR ALL TO authenticated USING(public.has_role(auth.uid(),'admin')) WITH CHECK(public.has_role(auth.uid(),'admin'));
CREATE TABLE public.categories(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),name text NOT NULL,slug text NOT NULL UNIQUE,image_url text);
GRANT SELECT ON public.categories TO anon; GRANT SELECT,INSERT,UPDATE,DELETE ON public.categories TO authenticated; GRANT ALL ON public.categories TO service_role;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
CREATE POLICY public_categories ON public.categories FOR SELECT TO anon,authenticated USING(true);
CREATE POLICY admin_categories ON public.categories FOR ALL TO authenticated USING(public.has_role(auth.uid(),'admin')) WITH CHECK(public.has_role(auth.uid(),'admin'));
CREATE TABLE public.brands(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),name text NOT NULL,slug text NOT NULL UNIQUE,logo_url text);
GRANT SELECT ON public.brands TO anon; GRANT SELECT,INSERT,UPDATE,DELETE ON public.brands TO authenticated; GRANT ALL ON public.brands TO service_role;
ALTER TABLE public.brands ENABLE ROW LEVEL SECURITY;
CREATE POLICY public_brands ON public.brands FOR SELECT TO anon,authenticated USING(true);
CREATE POLICY admin_brands ON public.brands FOR ALL TO authenticated USING(public.has_role(auth.uid(),'admin')) WITH CHECK(public.has_role(auth.uid(),'admin'));
CREATE TABLE public.orders(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid NOT NULL REFERENCES public.profiles(id),status text NOT NULL DEFAULT 'Pending Payment',total numeric NOT NULL DEFAULT 0,address jsonb NOT NULL DEFAULT '{}',courier text,tracking_url text,created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,UPDATE ON public.orders TO authenticated; GRANT ALL ON public.orders TO service_role;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
CREATE POLICY own_orders ON public.orders FOR SELECT TO authenticated USING(user_id=auth.uid());
CREATE POLICY admin_orders ON public.orders FOR ALL TO authenticated USING(public.has_role(auth.uid(),'admin')) WITH CHECK(public.has_role(auth.uid(),'admin'));
CREATE TABLE public.settings(key text PRIMARY KEY,value jsonb NOT NULL);
GRANT SELECT ON public.settings TO anon; GRANT SELECT,INSERT,UPDATE,DELETE ON public.settings TO authenticated; GRANT ALL ON public.settings TO service_role;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY public_settings ON public.settings FOR SELECT TO anon,authenticated USING(key IN ('store','shipping'));
CREATE POLICY admin_settings ON public.settings FOR ALL TO authenticated USING(public.has_role(auth.uid(),'admin')) WITH CHECK(public.has_role(auth.uid(),'admin'));
CREATE TABLE public.carts(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid UNIQUE,guest_token text UNIQUE,items jsonb NOT NULL DEFAULT '[]',updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT,UPDATE,DELETE ON public.carts TO authenticated; GRANT ALL ON public.carts TO service_role;
ALTER TABLE public.carts ENABLE ROW LEVEL SECURITY;
CREATE POLICY own_cart ON public.carts FOR ALL TO authenticated USING(user_id=auth.uid()) WITH CHECK(user_id=auth.uid());
CREATE INDEX products_status_idx ON public.products(status);
CREATE INDEX variants_product_idx ON public.product_variants(product_id);