import { useState } from 'react';
import { useNavigate } from '@tanstack/react-router';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { lovable } from '@/integrations/lovable';
import { useStore } from '@/components/store-shell';
import { Button } from '@/components/ui/button';
import { z } from 'zod';
import { money } from '@/lib/store';
export function AccountPage(){
 const {userName}=useStore();const navigate=useNavigate();const qc=useQueryClient();const [mode,setMode]=useState<'login'|'signup'|'forgot'>('login');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
 const {data:account}=useQuery({queryKey:['account',userName],enabled:!!userName,queryFn:async()=>{const {data:{user},error}=await supabase.auth.getUser();if(error||!user)throw new Error('Please sign in again.');await supabase.from('profiles').upsert({id:user.id,name:user.user_metadata?.['name']??'',mobile:user.user_metadata?.['mobile']??''},{onConflict:'id',ignoreDuplicates:true});const [profile,orders,addresses]=await Promise.all([supabase.from('profiles').select('*').eq('id',user.id).single(),supabase.from('orders').select('*').eq('user_id',user.id),supabase.from('addresses').select('*').eq('user_id',user.id)]);return {user,profile:profile.data,orders:orders.data??[],addresses:addresses.data??[]}}});
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage('');const values=Object.fromEntries(new FormData(e.currentTarget));try{const email=z.string().email().parse(values['email']);if(mode==='forgot'){const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:window.location.origin+'/reset-password'});if(error)throw error;setMessage('Check your email for a password reset link.');}else{const password=z.string().min(8,'Use a password with at least 8 characters.').parse(values['password']);if(mode==='signup'){const name=z.string().min(2).parse(values['name']);const mobile=z.string().regex(/^[6-9]\d{9}$/,'Enter a valid 10-digit Indian mobile number.').parse(values['mobile']);const {data,error}=await supabase.auth.signUp({email,password,options:{emailRedirectTo:window.location.origin+'/account',data:{name,mobile}}});if(error)throw error;setMessage(data.session?'Your account is ready.':'Check your email to confirm your account before signing in.');}else{const {error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error;await navigate({to:'/account'});}}}catch(error){setMessage(error instanceof Error?error.message:'Please check your details.')}finally{setBusy(false)}}
 if(userName)return <main className="wrap section"><div className="page-head"><h1>Your little corner</h1><p>Welcome, {account?.profile?.name||userName}.</p><Button variant="outline" onClick={async()=>{await qc.cancelQueries();qc.clear();await supabase.auth.signOut();navigate({to:'/auth',replace:true})}}>Sign out</Button></div><h2 className="font-display text-2xl">Your orders</h2>{account?.orders.length?<table className="admin-table"><thead><tr><th>Order</th><th>Status</th><th>Total</th></tr></thead><tbody>{account.orders.map(o=><tr key={o.id}><td>{o.id.slice(0,8)}</td><td>{o.status}</td><td>{money(o.total)}</td></tr>)}</tbody></table>:<p className="text-muted-foreground mb-8">No orders yet. Your pet’s next favourite is waiting.</p>}<h2 className="font-display text-2xl">Saved addresses</h2>{account?.addresses.map(a=><p key={a.id}>{a.name} · {a.address}, {a.city}, {a.state} {a.pincode}</p>)}<form className="form-grid max-w-2xl mt-5" onSubmit={async e=>{e.preventDefault();if(!account?.user)return;const f=Object.fromEntries(new FormData(e.currentTarget));try{const address=z.object({name:z.string().min(2),mobile:z.string().regex(/^[6-9]\d{9}$/),pincode:z.string().regex(/^\d{6}$/),address:z.string().min(5),city:z.string().min(2),state:z.string().min(2)}).parse(f);const {error}=await supabase.from('addresses').insert({...address,user_id:account.user.id});if(error)throw error;setMessage('Address saved.');qc.invalidateQueries({queryKey:['account']})}catch(error){setMessage(error instanceof Error?error.message:'Check your address.')}}}>{['name','mobile','pincode','address','city','state'].map(f=><label key={f} className="text-xs capitalize">{f}<input className="field mt-2" name={f} required placeholder={f==='mobile'?'10-digit mobile':f==='pincode'?'6-digit pincode':f}/></label>)}<Button type="submit">Save address</Button></form>{message&&<p className="form-message">{message}</p>}</main>;
 return <main><div className="auth-panel"><div className="eyebrow">Welcome to the family</div><h1>{mode==='signup'?'A home for every paw':mode==='forgot'?'Let’s get you back in':'Lovely to see you again'}</h1><p className="text-muted-foreground text-xs">{mode==='signup'?'Create your L.W Pet Care account.':'Sign in for your orders and saved addresses.'}</p><form onSubmit={submit}>{mode==='signup'&&<><label htmlFor="name">Your name</label><input id="name" name="name" className="field" required/><label htmlFor="mobile">Mobile number</label><input id="mobile" name="mobile" type="tel" className="field" pattern="[6-9][0-9]{9}" maxLength={10} required/></>}<label htmlFor="email">Email address</label><input id="email" name="email" type="email" className="field" autoComplete="email" required/>{mode!=='forgot'&&<><label htmlFor="password">Password</label><input id="password" name="password" type="password" className="field" autoComplete={mode==='signup'?'new-password':'current-password'} minLength={8} required/></>}<Button type="submit" disabled={busy} className="w-full mt-5">{busy?'Please wait…':mode==='signup'?'Create account':mode==='forgot'?'Send reset link':'Sign in'}</Button></form>{mode!=='forgot'&&<Button variant="outline" className="w-full mt-3" onClick={async()=>{const result=await lovable.auth.signInWithOAuth('google',{redirect_uri:window.location.origin+'/account'});if(result.error)setMessage(result.error.message)}}>Continue with Google</Button>}{message&&<p className="form-message" role="status">{message}</p>}<div className="flex flex-col mt-3"><Button variant="link" onClick={()=>{setMode(mode==='signup'?'login':'signup');setMessage('')}}>{mode==='signup'?'Already family? Sign in':'New here? Create an account'}</Button><Button variant="link" onClick={()=>{setMode('forgot');setMessage('')}}>Forgot password?</Button></div></div></main>
}
