import { useState } from 'react';
import { Link } from '@tanstack/react-router';
import { useSuspenseQuery } from '@tanstack/react-query';
import { PackageSearch, ArrowRight } from 'lucide-react';
import { catalogueOptions } from '@/lib/catalogue.functions';
import { brands, categories, money, whatsapp } from '@/lib/store';
import { Button } from '@/components/ui/button';
export function ShopPage({title,pet,category,brand}:{title:string;pet?:string;category?:string;brand?:string}){
 const {data:products}=useSuspenseQuery(catalogueOptions);const [chosenBrands,setChosenBrands]=useState<string[]>([]);const [stage,setStage]=useState<string[]>([]);const [sort,setSort]=useState('newest');const [stock,setStock]=useState(false);
 const categoryName=categories.find(c=>c.slug===category)?.name;
 const results=products.filter(p=>(!pet||p.pet_type===pet)&&(!brand||brand==='all'||p.brand.toLowerCase().replace(/[^a-z0-9]+/g,'-')===brand)&&(!categoryName||p.category===categoryName||p.category===categoryName.split(' &')[0])&&(!chosenBrands.length||chosenBrands.includes(p.brand))&&(!stage.length||stage.includes(p.life_stage))&&(!stock||p.product_variants.some(v=>v.stock>0))).sort((a,b)=>sort==='low'?(a.product_variants[0]?.price??0)-(b.product_variants[0]?.price??0):sort==='high'?(b.product_variants[0]?.price??0)-(a.product_variants[0]?.price??0):b.created_at.localeCompare(a.created_at));
 const toggle=(name:string,values:string[],set:(v:string[])=>void)=>set(values.includes(name)?values.filter(v=>v!==name):[...values,name]);
 return <main className="wrap"><div className="page-head"><div className="eyebrow">Home / {title}</div><h1>{title}</h1><p>Thoughtful essentials for the pets you call family.</p></div><div className="shop-layout"><aside><div className="filter-group"><h3>Brand</h3>{brands.slice(0,8).map(b=><label key={b}><input type="checkbox" checked={chosenBrands.includes(b)} onChange={()=>toggle(b,chosenBrands,setChosenBrands)}/>{b}</label>)}</div><div className="filter-group"><h3>Life stage</h3>{['puppy','kitten','adult','senior'].map(s=><label key={s}><input type="checkbox" checked={stage.includes(s)} onChange={()=>toggle(s,stage,setStage)}/>{s[0]?.toUpperCase()}{s.slice(1)}</label>)}</div><div className="filter-group"><h3>Availability</h3><label><input type="checkbox" checked={stock} onChange={e=>setStock(e.target.checked)}/>In stock only</label><Button variant="link" onClick={()=>{setChosenBrands([]);setStage([]);setStock(false)}}>Clear filters</Button></div></aside><div><div className="shop-top"><span className="text-xs text-muted-foreground">{results.length} products</span><select aria-label="Sort products" value={sort} onChange={e=>setSort(e.target.value)}><option value="newest">Newest first</option><option value="low">Price: low to high</option><option value="high">Price: high to low</option></select></div>{results.length?<div className="product-grid">{results.map(p=><Link className="product-card" key={p.id} to="/product/$slug" params={{slug:p.slug}}>{p.image_url&&<img src={p.image_url} alt={p.name} loading="lazy"/>}<small>{p.brand}</small><h3>{p.name}</h3><p>{p.product_variants[0]?.pack_size}</p>{p.product_variants[0]?.price!=null&&<strong>{money(p.product_variants[0].price)}</strong>}<span className="inline-flex items-center gap-2 mt-4 text-xs">View product <ArrowRight size={13}/></span></Link>)}</div>:<div className="empty-state"><PackageSearch size={42}/><h2>{chosenBrands.length||stage.length||stock?'No matching products':'Good things are on their way'}</h2><p>{chosenBrands.length||stage.length||stock?'Try adjusting your filters.':'Our online shelves are getting ready. In the meantime, we’re here to help you find what your pet needs.'}</p><Button asChild><a href={whatsapp} target="_blank" rel="noreferrer">Ask us on WhatsApp <ArrowRight/></a></Button></div>}</div></div></main>
}
export function CatalogueError(){return <div className="wrap section"><h1>Our shelves are temporarily unavailable</h1><p>Please try again shortly, or call 9217962828.</p></div>}
