import { Link } from '@tanstack/react-router';
import { Search, UserRound, ShoppingBag, Phone, ChevronDown, Scissors, Truck, MessageCircle, X, PawPrint } from 'lucide-react';
import { useState, createContext, useContext, useEffect, type ReactNode } from 'react';
import { Button } from '@/components/ui/button';
import logo from '@/assets/logo.png.asset.json';
import { whatsapp, categories, brands } from '@/lib/store';
import { supabase } from '@/integrations/supabase/client';
const StoreContext=createContext<{userName:string|null;cartOpen:boolean;setCartOpen:(open:boolean)=>void}>({userName:null,cartOpen:false,setCartOpen:()=>{}});
export const useStore=()=>useContext(StoreContext);
export function StoreShell({children}:{children:ReactNode}){
 const [search,setSearch]=useState('');const [cartOpen,setCartOpen]=useState(false);const [userName,setUserName]=useState<string|null>(null);
 useEffect(()=>{const refresh=()=>supabase.auth.getUser().then(({data})=>setUserName(data.user?.user_metadata?.['name']??data.user?.email??null));refresh();window.addEventListener('lw-auth-change',refresh);return ()=>window.removeEventListener('lw-auth-change',refresh)},[]);
 const matches=[...categories.map(c=>({name:c.name,slug:c.slug,type:'category'})),...brands.map(name=>({name,slug:name.toLowerCase().replace(/[^a-z0-9]+/g,'-'),type:'brand'}))].filter(c=>c.name.toLowerCase().includes(search.toLowerCase())).slice(0,6);
 return <StoreContext.Provider value={{userName,cartOpen,setCartOpen}}><div className="announcement"><Truck size={13}/> Free home delivery across Delhi NCR <span>·</span> A little love, delivered to your door</div>
 <header><div className="wrap header-main"><Link to="/" aria-label="L.W Pet Care home"><img src={logo.url} className="logo" alt="L.W Pet Care — We treat your pets like family"/></Link><div className="search"><div className="search-box"><Search size={18}/><input aria-label="Search products and brands" placeholder="Search for food, treats, toys & a little happiness..." value={search} onChange={e=>setSearch(e.target.value)}/>{search&&<Button variant="ghost" size="icon" aria-label="Clear search" onClick={()=>setSearch('')}><X/></Button>}</div>{search&&<div className="search-results">{matches.length?matches.map(m=>m.type==='brand'?<Link key={m.slug} to="/brand/$name" params={{name:m.slug}} onClick={()=>setSearch('')}>{m.name}</Link>:<Link key={m.slug} to="/category/$name" params={{name:m.slug}} onClick={()=>setSearch('')}>{m.name}</Link>):<p className="p-3 text-muted-foreground">No matching categories or brands.</p>}</div>}</div><div className="header-actions"><a href="tel:+919217962828" className="header-action" title="Call 9217962828"><Phone size={19}/><span>Need help?<br/><strong>9217962828</strong></span></a><Link to="/account" className="header-action" title={userName?'My account':'Sign in'}><UserRound size={22}/><span>{userName?'My account':'Sign in'}</span></Link><Button variant="ghost" size="icon" onClick={()=>setCartOpen(true)} aria-label="Open shopping bag" title="Shopping bag"><ShoppingBag size={23}/></Button></div></div><nav className="nav"><div className="wrap nav-inner"><Link to="/dogs">Dogs <ChevronDown size={12}/></Link><Link to="/cats">Cats <ChevronDown size={12}/></Link><Link to="/category/$name" params={{name:'dog-food'}}>Pet Food <ChevronDown size={12}/></Link><Link to="/category/$name" params={{name:'treats'}}>Treats & Chews</Link><Link to="/category/$name" params={{name:'toys'}}>Toys & Accessories</Link><Link to="/category/$name" params={{name:'vet-diets'}}>Vet Diets</Link><Link to="/brand/$name" params={{name:'all'}}>Shop by Brand <ChevronDown size={12}/></Link><Link to="/grooming" className="groom-link"><Scissors size={14}/> Grooming Services</Link></div></nav></header>
 {children}
 <footer className="footer"><div className="wrap"><div className="footer-grid"><div><img src={logo.url} className="footer-logo" alt="Louis Wilson Pet Care"/><p>A little care. A lot of love.<br/>We treat your pets like family.</p></div><div><h4>Explore the store</h4><Link to="/dogs">Shop for dogs</Link><Link to="/cats">Shop for cats</Link><Link to="/grooming">Grooming services</Link><Link to="/about">Our story</Link></div><div><h4>Here to help</h4><Link to="/contact">Contact us</Link><Link to="/shipping-policy">Shipping policy</Link><Link to="/refund-policy">Returns & refunds</Link><Link to="/privacy-policy">Privacy policy</Link><Link to="/terms">Terms & conditions</Link></div><div><h4>Your neighbourhood pet store</h4><p>B-129, Ground Floor, Anand Vihar,<br/>Delhi 110092</p><a href="tel:+919217962828">Call: +91 9217962828</a><a href={whatsapp} target="_blank" rel="noreferrer">Chat with us on WhatsApp ↗</a><a href="https://instagram.com/l.w_pet_care" target="_blank" rel="noreferrer">Instagram · @l.w_pet_care</a></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Louis Wilson Pet Care. Made with love for paws.</span><span>Prices in INR · GST included</span></div></div></footer><a href={whatsapp} target="_blank" rel="noreferrer" className="whatsapp" aria-label="Get help on WhatsApp" title="Chat on WhatsApp"><MessageCircle size={25}/></a>
 {cartOpen&&<div className="drawer-overlay" onClick={()=>setCartOpen(false)}><div role="dialog" aria-modal="true" aria-label="Shopping bag" className="cart-drawer" onClick={e=>e.stopPropagation()}><header><h2>Your shopping bag</h2><Button variant="ghost" size="icon" aria-label="Close bag" onClick={()=>setCartOpen(false)}><X/></Button></header><div className="empty-state"><ShoppingBag size={40}/><h2>A little room for happiness</h2><p>Your bag is empty.<br/>Find something your pet will love.</p><Button asChild onClick={()=>setCartOpen(false)}><Link to="/dogs">Explore the store</Link></Button></div><Button variant="link" asChild className="mt-6"><Link to="/cart" onClick={()=>setCartOpen(false)}>View shopping bag</Link></Button></div></div>}
 </StoreContext.Provider>;
}
